### ISSUE TITLE
Is it possible to configure explicit the rootpage per language/country?

### ISSUE THREAD

**Issue by vaxul** [urbantrout/site-language-redirection#5]
I have a project which should have currently 3 page trees:

* PAGE 1
** domain.com/en-us/ - hreflang: en-US
** domain.com/en-ca/ - hreflang: en-CA
* PAGE 2
** domain.com/de-de/ - hreflang: de-DE
** domain.com/fr-fr/ - hreflang: fr-FR
** domain.com/it-it/ - hreflang: it-IT
* PAGE 3
* domain.com/en/ - hreflang: en-US (would be changeable in the moment)

`PAGE 3` is kind of "rest of the world / international" page.

Would this manageable with this extension?

Best regards

**Comment by urbantrout** [comment]
I haven't tested the extension with a multi tree setup yet. But I think that it will not work at the moment.

This is definitely something I consider implementing!

**Comment by urbantrout** [comment]
How did you set up your site configurations? I just tried to create a multitree setup but it is not possible to create a site configuration without the default language. Did you disable English for **PAGE 2** in your example?

Here is my test setup:

![Bildschirmfoto am 2019-10-27 um 12 42 36](https://user-images.githubusercontent.com/10465787/67634051-a0ae6c80-f8b7-11e9-826e-bb5b80ed264c.png)

**Comment by urbantrout** [comment]
Ignore the first site configuration. I was thinking of creating "Site Groups" to groups site configurations for multitree redirects. In the above example this would be a group with ID 61 and 59.

You will be redirected only to pages in the same site group. This allows single tree and mult itree settings in parallel.

**Comment by vaxul** [comment]
So there are 3 site configurations, while the default language might change in each tree, so:

* PAGE 1
** domain.com/en-us/ - hreflang: en-US (default)
** domain.com/en-ca/ - hreflang: en-CA
* PAGE 2
** domain.com/de-de/ - hreflang: de-DE (default)
** domain.com/fr-fr/ - hreflang: fr-FR
** domain.com/it-it/ - hreflang: it-IT
* PAGE 3
* domain.com/en/ - hreflang: en-US (would be changeable in the moment)  (default)

**Comment by urbantrout** [comment]
How did you manage to set the default language to anything other than English? What TYPO3 version are you using? I cannot save the site configuration without adding English as default language. That's why I disabled English in the screenshot above.

**Comment by vaxul** [comment]
You can just change the `typo3language` on the default language:
![image](https://user-images.githubusercontent.com/3798226/67748024-4f72ba00-fa2a-11e9-8aaf-44d014ad9c38.png)

I've looked into the code from this extension. It uses the `hreflang` setting from site configuration.

Maybe it would be an idea to add an option, which would resolve the correct root page by the `base` of the site configuration.
So it can' be confused by two page trees with the same default hreflang, since the `base` should be unique.

What do you think?

**Comment by urbantrout** [comment]
Strange. whenever I set the language to anything other than English and click on save, TYPO3 adds a second language (English). Seems like some kind of form validation problem.

**Comment by vaxul** [comment]
Sounds stange. A site config.yml like this would be perfectly valid:
```yml
base: '/'
baseVariants: {  }
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=101'
languages:
  -
    title: Italy
    enabled: true
    base: /it-it/
    typo3Language: it
    locale: it_IT.UTF-8
    iso-639-1: it
    navigationTitle: Italy
    hreflang: it-IT
    direction: ltr
    flag: it
    languageId: '0'
rootPageId: 100
routes: {  }
```
